name: release

on: push

jobs:
  ubuntu-release:
    runs-on: ubuntu-latest
    env:
      YML2_PATH: /home/runner/venv/bin
      PREFIX: /home/runner/install
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install asn1c
      - run: |
          python -m venv /home/runner/venv
          . /home/runner/venv/bin/activate
          pip install git+https://github.com/plancksecurity/foundation-yml2
      - run: |
          . /home/runner/venv/bin/activate
          make -j8
          make install
      - name: archive artifacts on sha
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{ github.sha }}
          path: /home/runner/install
      - name: archive artifacts on tag
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{ github.ref }}
          path: install


