name: release

on: push

jobs:
  ubuntu-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PREFIX: /home/runner/install
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.ALL_REPO_ACCESS_TOKEN }}
      - name: Configure
        run: |
          sh autogen.sh
          ./configure --prefix=/home/runner/install
      - name: Build
        run: make
      - name: Install
        run: make install
      - name: Compress
        run: |
          cd /home/runner/install
          tar cvj . > ../ubuntu-release.tar.bz2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.head_ref || github.ref_name }}
          files: /home/runner/ubuntu-release.tar.bz2
          fail_on_unmatched_files: true

  windows-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.ALL_REPO_ACCESS_TOKEN }}
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Upgrade
        run: |
          $devenv = & vswhere.exe '-property' productPath
          Start-Process -FilePath $devenv -ArgumentList 'build-windows\libetpan.sln /Upgrade' -Wait
      - name: Build
        run: msbuild build-windows\libetpan.sln /p:Platform=Win32 /p:Configuration=Release
      - name: Compress
        run: Compress-Archive -Path build-windows\Release\* -Destination windows-release.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.head_ref || github.ref_name }}
          files: windows-release.zip
          fail_on_unmatched_files: true

